apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 {{- if lower .Values.sename}}
 name: ingress-router-backend-{{ lower .Values.sename }}
 {{- else }}
 name: ingress-router
 {{- end }}
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
  rules:
  {{- if lower .Values.sename}}
  - host: {{ lower .Values.sename }}.backend.devx.harness-demo.site
  {{- else }}
  - host: backend.devx.harness-demo.site
  {{- end }}
    http:
     paths:
     - pathType: ImplementationSpecific
       backend:
       {{- if lower .Values.sename}}
          service:
             name: web-devxbackend-{{lower .Values.sename }}-svc
             port:
               number: 80
       {{- else }}
          service:
             name:web-devxbackend-svc
             port:
               number: 80
       {{- end }}
